import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useESP8266 } from './hooks'
const Home: NextPage = () => {
  const { lecture, status } = useESP8266('mqtt://localhost:1884', { clientId: 'web_server'})
  return (
    <div className={styles.container}>
      <Head>
        <title>Sensor de temperatura y humedad</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.nav}>
        <h2>ESP8266</h2>
        <p>{status}</p>
      </div>
      <main className={styles.main}>
        <h1 className={styles.title}>
          { lecture.temperature }°C
        </h1>

        <p className={styles.description}>
          { lecture.humidity }% humedad
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/Ridnois/mqtt_client.git" className={styles.card}>
            <h2>Documentación &rarr;</h2>
            <p>Haz click aquí para ingresar al repositorio de este proyecto</p>
          </a>
          
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
